### ISSUE TITLE
Define a general roadmap from member ideas

### ISSUE THREAD

**Issue by d4n13lbc** [icesi-devops/club2020b-content#2]
We will collect here initial ideas for youtube live, webinars, podcasts
Base on these ideas we will create a roadmap to follow for content generation
Consolidate the content for the first topic, plan and do the presentation to the public
Get sponsor
Prepare for the next presentation

**Comment by d4n13lbc** [comment]
Ideas:
Domain Driven Design
GitOps
Monitoring Stacks (Elasticsearch+Kibana, Prometheus+Grafana)
ChatOps

**Comment by willy23martin** [comment]
Version Control - GitFlow - Teams work.
Software Development Lifecycle in DevOps era (Pipelines):
  - Travis CI.
  - GitHub Actions.
  - GitLab CI/CD Pipelines.

Databases - NoSQL and Polyglot Databases [Microsoft SQL Server and Document Based (MongoDB)].
Web Development - Frontend and Backend: Spring Boot (Java) - Ruby On Rails (Ruby) - NodeJS (Express, Javascript), Angular.

**Comment by jmaquin0** [comment]
Ideas.
Messages Queues and message brokers.
--> rabbitMQ vs Kafka
REST APIs 
GraphQL
DDD (Strategic)

**Comment by yorjaggy** [comment]
- The Future of K8S
- AIOps
- IaaC (Pulumi)
- ETL
- eBPF
- Building internal tools for TI/DevOps for "free"
- Trending and comparison between Cloud providers (Why and how to pick)
- From Nothing to Everything, your path to implementing DevOps

**Comment by d4n13lbc** [comment]
In summary, we are going to start collecting lessons learned from our experience toward a DevOps culture. This will be the input for the first presentation of the group. Also, these cases will serve as a basis for the presentations/content roadmap.
